#!/usr/bin/env bash
# =============================================================================
# BASE v2.0 – Directory Structure Setup Script
# Project root: ~/Caravel/secure_boot_caravel
#
# WHAT THIS SCRIPT DOES:
#   1. Archives v1.0 RTL files (non-destructive – originals are preserved)
#   2. Creates the v2.0 directory partition under verilog/rtl/
#   3. Copies v1.0 core files into their new v2.0 locations
#   4. Creates placeholder files for new v2.0 modules
#   5. Creates the new cocotb test directory for Wishbone register map tests
#   6. Prints a confirmation tree at the end
#
# WHAT THIS SCRIPT DOES NOT DO:
#   - It does NOT modify any existing file content
#   - It does NOT touch verilog/gl/ (gate-level – regenerated by OpenLane)
#   - It does NOT modify openlane/ config (that is the next step)
#   - It does NOT delete anything
#
# HOW TO RUN:
#   cd ~/Caravel/secure_boot_caravel
#   chmod +x setup_base_v2.sh
#   bash setup_base_v2.sh
# =============================================================================

set -e  # exit on any error
PROJECT_ROOT="$HOME/Caravel/secure_boot_caravel"

echo ""
echo "============================================================"
echo "  BASE v2.0 – Directory Partition Setup"
echo "  Project root: $PROJECT_ROOT"
echo "============================================================"
echo ""

cd "$PROJECT_ROOT"

# ── STEP 1: Archive v1.0 RTL ─────────────────────────────────────────────────
echo "[1/6] Archiving v1.0 RTL files..."

mkdir -p verilog/rtl/archive_v1

# Copy (not move) – originals stay in place until OpenLane config is updated
cp verilog/rtl/caravel_secure_boot.sv      verilog/rtl/archive_v1/caravel_secure_boot.sv
cp verilog/rtl/secure_boot_system_wrapper.sv verilog/rtl/archive_v1/secure_boot_system_wrapper.sv
cp verilog/rtl/secure_boot_fsm.sv          verilog/rtl/archive_v1/secure_boot_fsm.sv
cp verilog/rtl/group_fsm.sv                verilog/rtl/archive_v1/group_fsm.sv
cp verilog/rtl/user_project_wrapper.v      verilog/rtl/archive_v1/user_project_wrapper.v

echo "    -> v1.0 files archived to verilog/rtl/archive_v1/"

# ── STEP 2: Create v2.0 RTL subdirectory partition ───────────────────────────
echo ""
echo "[2/6] Creating v2.0 RTL directory structure..."

# Control plane (new module)
mkdir -p verilog/rtl/control_plane

# Core secure boot logic (unchanged, just re-homed)
mkdir -p verilog/rtl/secure_boot_core

# Top-level wrapper
# (user_project_wrapper.v stays in verilog/rtl/ – Caravel convention requires it there)

# Future component placeholders
mkdir -p verilog/rtl/accelerator
mkdir -p verilog/rtl/mmio_engine

echo "    -> verilog/rtl/control_plane/      created"
echo "    -> verilog/rtl/secure_boot_core/   created"
echo "    -> verilog/rtl/accelerator/        created (placeholder)"
echo "    -> verilog/rtl/mmio_engine/        created (placeholder)"

# ── STEP 3: Copy core v1.0 files into their v2.0 home ────────────────────────
echo ""
echo "[3/6] Populating secure_boot_core/ with v1.0 source files..."

cp verilog/rtl/secure_boot_system_wrapper.sv verilog/rtl/secure_boot_core/secure_boot_system_wrapper.sv
cp verilog/rtl/secure_boot_fsm.sv            verilog/rtl/secure_boot_core/secure_boot_fsm.sv
cp verilog/rtl/group_fsm.sv                  verilog/rtl/secure_boot_core/group_fsm.sv

echo "    -> secure_boot_system_wrapper.sv   copied"
echo "    -> secure_boot_fsm.sv              copied"
echo "    -> group_fsm.sv                    copied"

# ── STEP 4: Create new v2.0 module placeholders ──────────────────────────────
echo ""
echo "[4/6] Creating v2.0 module placeholder files..."

# secure_boot_control_plane.sv – new top-level wrapper
cat > verilog/rtl/control_plane/secure_boot_control_plane.sv << 'PLACEHOLDER'
// =============================================================================
// secure_boot_control_plane.sv
// BASE v2.0 – Wishbone Control Plane Wrapper
//
// STATUS: PLACEHOLDER – implementation pending
//
// This module will:
//   - Instantiate secure_boot_system_wrapper
//   - Implement 32-bit Wishbone slave (classic mode, single-cycle ACK)
//   - Expose register map: GLOBAL_STATE(0x00), STATUS_FLAGS(0x04),
//     TIMEOUTS(0x08), CONTROL(0x0C)
//   - Preserve GPIO mapping io_in[7:20] / io_out[21:28]
//   - Drive user_irq[0] on critical events
// =============================================================================
`timescale 1ns/1ps
`default_nettype none

module secure_boot_control_plane (
    // TODO: implement – see BASE_v2.0_Implementation_Spec.docx
);

endmodule
`default_nettype wire
PLACEHOLDER

echo "    -> control_plane/secure_boot_control_plane.sv  created (placeholder)"

# Placeholder README for accelerator
cat > verilog/rtl/accelerator/README.md << 'PLACEHOLDER'
# Accelerator Module (BASE v2.0 – Future)

This directory is reserved for a hardware accelerator component.

Integration notes (from BASE v2.0 spec):
- Wishbone base address: start at offset 0x10 or use a separate base address
- IRQ assignment: user_irq[1] is available
- GPIO: io_in[0:6] and io_out[29:37] are available
- user_clock2 is available as a secondary clock domain

No RTL exists here yet. Populate when scope is confirmed.
PLACEHOLDER

# Placeholder README for mmio_engine
cat > verilog/rtl/mmio_engine/README.md << 'PLACEHOLDER'
# MMIO Engine (BASE v2.0 – Future)

This directory is reserved for a memory-mapped I/O engine component.

Integration notes (from BASE v2.0 spec):
- Wishbone base address: assign after accelerator, or use crossbar
- IRQ assignment: user_irq[2] is available
- la_data_out[127:0] is fully available for debug visibility

No RTL exists here yet. Populate when scope is confirmed.
PLACEHOLDER

echo "    -> accelerator/README.md                       created"
echo "    -> mmio_engine/README.md                       created"

# ── STEP 5: Create v2.0 cocotb test directory ────────────────────────────────
echo ""
echo "[5/6] Creating v2.0 cocotb test directories..."

# Wishbone register map test
mkdir -p verilog/dv/cocotb/user_proj_tests/wb_regmap
cat > verilog/dv/cocotb/user_proj_tests/wb_regmap/wb_regmap.yaml << 'PLACEHOLDER'
# BASE v2.0 – Wishbone Register Map Test
# STATUS: PLACEHOLDER – test implementation pending
#
# Test plan:
#   1. Read GLOBAL_STATE (0x00) after reset – expect FSM in BOOT state
#   2. Read STATUS_FLAGS (0x04) after reset – expect all stickies = 0
#   3. Read TIMEOUTS (0x08) – expect counters at 0
#   4. Write CONTROL (0x0C) = 0x1F – clear all shadow stickies (no-op at reset)
#   5. Assert tamper_in, read STATUS_FLAGS – expect sw_sticky_tamper = 1
#   6. Assert user_irq[0] = 1 after sticky set
#   7. Write CONTROL[0] = 1 – clear tamper sticky
#   8. Confirm user_irq[0] deasserts after all stickies cleared
PLACEHOLDER

cat > verilog/dv/cocotb/user_proj_tests/wb_regmap/wb_regmap.py << 'PLACEHOLDER'
# BASE v2.0 – Wishbone Register Map Test
# STATUS: PLACEHOLDER – implementation pending
# See wb_regmap.yaml for test plan
PLACEHOLDER

cat > verilog/dv/cocotb/user_proj_tests/wb_regmap/wb_regmap.c << 'PLACEHOLDER'
/* BASE v2.0 – Wishbone Register Map Firmware Test
 * STATUS: PLACEHOLDER – implementation pending
 */
PLACEHOLDER

# GPIO passthrough test
mkdir -p verilog/dv/cocotb/user_proj_tests/gpio_passthrough
cat > verilog/dv/cocotb/user_proj_tests/gpio_passthrough/gpio_passthrough.yaml << 'PLACEHOLDER'
# BASE v2.0 – GPIO Passthrough Test
# STATUS: PLACEHOLDER – test implementation pending
#
# Test plan:
#   1. Drive each io_in[7:20] high one at a time
#   2. Confirm corresponding internal signal reaches secure_boot_system_wrapper
#   3. After boot sequence, confirm io_out[21:28] carry correct boot outputs
#   4. Confirm io_out[0:20] remain LOW
#   5. Confirm io_out[29:37] remain LOW
PLACEHOLDER

cat > verilog/dv/cocotb/user_proj_tests/gpio_passthrough/gpio_passthrough.py << 'PLACEHOLDER'
# BASE v2.0 – GPIO Passthrough Test
# STATUS: PLACEHOLDER – implementation pending
PLACEHOLDER

echo "    -> user_proj_tests/wb_regmap/        created (placeholder)"
echo "    -> user_proj_tests/gpio_passthrough/ created (placeholder)"

# ── STEP 6: Print confirmation tree ──────────────────────────────────────────
echo ""
echo "[6/6] Confirming directory structure..."
echo ""
echo "─────────────────────────────────────────────────────────"
echo "  BASE v2.0 – verilog/ partition"
echo "─────────────────────────────────────────────────────────"

find verilog/rtl verilog/dv/cocotb/user_proj_tests \
     -not -path '*/\.*' \
     | sort \
     | sed 's|[^/]*/|  |g; s|  \([^/]*$\)|  └─ \1|'

echo ""
echo "─────────────────────────────────────────────────────────"
echo ""
echo "✅  Setup complete. Summary of what was created:"
echo ""
echo "  ARCHIVED (v1.0 originals preserved):"
echo "    verilog/rtl/archive_v1/            <- do not delete until GL verified"
echo ""
echo "  CORE FILES (v1.0, copied to new home – do not modify):"
echo "    verilog/rtl/secure_boot_core/      <- secure_boot_system_wrapper + FSMs"
echo ""
echo "  NEW v2.0 FILES (placeholders – implementation next step):"
echo "    verilog/rtl/control_plane/         <- secure_boot_control_plane.sv"
echo "    verilog/rtl/user_project_wrapper.v <- to be updated (step 3)"
echo ""
echo "  FUTURE PLACEHOLDERS (out of scope this revision):"
echo "    verilog/rtl/accelerator/           <- README only"
echo "    verilog/rtl/mmio_engine/           <- README only"
echo ""
echo "  NEW TESTS (placeholders – implementation pending):"
echo "    verilog/dv/cocotb/user_proj_tests/wb_regmap/"
echo "    verilog/dv/cocotb/user_proj_tests/gpio_passthrough/"
echo ""
echo "─────────────────────────────────────────────────────────"
echo "  NEXT STEP: Update verilog/includes/includes.rtl.caravel_user_project"
echo "  to point to new file paths, then implement"
echo "  secure_boot_control_plane.sv and update user_project_wrapper.v"
echo "─────────────────────────────────────────────────────────"
echo ""
