`timescale 1ns/1ps
`default_nettype none
module caravel_secure_boot (
    inout VPWR, inout VGND,
    input  logic        clk,
    input  logic        reset,
    input  logic        fw_ok,
    input  logic        fw_fail,
    input  logic        size_mismatch,
    input  logic        hdr_parse_fail,
    input  logic        power_glitch,
    input  logic        clock_glitch,
    input  logic        warm_reset_req,
    input  logic        cold_reset_req,
    input  logic        global_pin_ok,
    input  logic        unlock_req,
    input  logic        file_denied,
    input  logic        group_autolock,
    input  logic        tamper_in,
    input  logic        illegal_in,
    output logic        unlock_enable,
    output logic        debug_enable,
    output logic        safe_led,
    output logic        fsm_error,
    output logic        security_breach,
    output logic        group_unlocked,
    output logic        group_suspended,
    output logic        group_error
);

secure_boot_system_wrapper u_system (
    .clk                    (clk),
    .reset                  (reset),
    .fw_ok                  (fw_ok),
    .fw_fail                (fw_fail),
    .size_mismatch          (size_mismatch),
    .hdr_parse_fail         (hdr_parse_fail),
    .power_glitch           (power_glitch),
    .clock_glitch           (clock_glitch),
    .warm_reset_req         (warm_reset_req),
    .cold_reset_req         (cold_reset_req),
    .global_pin_ok          (global_pin_ok),
    .unlock_req             (unlock_req),
    .file_denied            (file_denied),
    .group_autolock         (group_autolock),
    .tamper_in              (tamper_in),
    .illegal_in             (illegal_in),
    .unlock_enable          (unlock_enable),
    .debug_enable           (debug_enable),
    .safe_led               (safe_led),
    .fsm_error              (fsm_error),
    .security_breach        (security_breach),
    .group_unlocked         (group_unlocked),
    .group_suspended        (group_suspended),
    .group_error            (group_error),
    .global_state_bits      (),
    .global_state_boot      (),
    .global_state_locked    (),
    .global_state_authorized(),
    .global_state_safe_mode (),
    .global_state_escalated (),
    .global_timeout_count   (),
    .group_state_bits       (),
    .group_state_disabled   (),
    .group_state_locked     (),
    .group_state_unlocked   (),
    .group_state_suspended  (),
    .group_locked           (),
    .sticky_tamper          (),
    .sticky_illegal         ()
);
endmodule
`default_nettype wire
